function zdot = bicycle_dynamics(I33,Tr,V,df,dr,m,psi,theta,thetadot)
%BICYCLE_DYNAMICS
%    ZDOT = BICYCLE_DYNAMICS(I33,Tr,V,DF,DR,M,PSI,THETA,THETADOT)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    01-Mar-2024 22:08:20

t2 = cos(theta);
t3 = sin(theta);
t4 = df.^2;
t5 = dr.^2;
t6 = t2.^2;
t7 = t2.^3;
t8 = 1.0./t2;
zdot = [V.*cos(psi);V.*sin(psi);(t8.*(Tr.*t4.*t7+Tr.*t5.*t7-I33.*V.*t3.*thetadot+Tr.*df.*dr.*t7.*2.0-V.*m.*t3.*t5.*thetadot))./(I33-I33.*t6+m.*t5+m.*t4.*t6+df.*dr.*m.*t6.*2.0);(V.*t3.*t8)./(df+dr)];
end
