function statedot = Bi_steer_3D_DAE(I11,V,Vdot,df,dr,g,h,m,phi,phidot,psi,theta_F,theta_R,theta_Fdot,theta_Rdot)
%Bi_steer_3D_DAE
%    STATEDOT = Bi_steer_3D_DAE(I11,V,Vdot,DF,DR,G,H,M,PHI,PHIDOT,PSI,theta_F,theta_R,theta_Fdot,theta_Rdot)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    24-Feb-2024 13:55:56

t2 = cos(phi);
t3 = cos(psi);
t4 = cos(theta_F);
t5 = cos(theta_R);
t6 = sin(phi);
t7 = sin(psi);
t8 = sin(theta_F);
t9 = sin(theta_R);
t10 = df+dr;
t11 = V.^2;
t12 = df.^2;
t13 = dr.^2;
t14 = theta_F.*2.0;
t17 = -theta_R;
t15 = t4.^2;
t16 = t5.^2;
t19 = 1.0./t10;
t20 = t14+t17;
t18 = 1.0./t15;
mt1 = [V.*(t3.*t5-t7.*t9);V.*(t3.*t9+t5.*t7);Vdot;(V.*t19.*sin(t17+theta_F))./t4;t18.*t19.*(Vdot.*t9-Vdot.*sin(t20)+V.*theta_Rdot.*cos(t20)-V.*t5.*theta_Fdot.*2.0+V.*t5.*theta_Rdot).*(-1.0./2.0);phidot];
mt2 = [(h.*m.*t18.*t19.^2.*(g.*t6.*t12.*t15+g.*t6.*t13.*t15+df.*dr.*g.*t6.*t15.*2.0+Vdot.*t2.*t9.*t12.*t15+V.*t2.*t5.*t13.*theta_Fdot+h.*t2.*t6.*t11.*t15+h.*t2.*t6.*t11.*t16+df.*t2.*t4.*t8.*t11.*t16-df.*t2.*t5.*t9.*t11.*t15+dr.*t2.*t4.*t8.*t11.*t16-dr.*t2.*t5.*t9.*t11.*t15-h.*t2.*t6.*t11.*t15.*t16.*2.0+Vdot.*df.*dr.*t2.*t9.*t15+V.*df.*dr.*t2.*t5.*theta_Fdot+Vdot.*t2.*t4.*t5.*t8.*t13+V.*t2.*t5.*t12.*t15.*theta_Rdot+Vdot.*df.*dr.*t2.*t4.*t5.*t8+V.*df.*dr.*t2.*t5.*t15.*theta_Rdot-V.*t2.*t4.*t8.*t9.*t13.*theta_Rdot-V.*df.*dr.*t2.*t4.*t8.*t9.*theta_Rdot-h.*t2.*t4.*t5.*t6.*t8.*t9.*t11.*2.0))./(I11+h.^2.*m);theta_Rdot;theta_Fdot];
statedot = [mt1;mt2];
end
