function phiddot = phiddot(I11,V,Vdot,df,dr,g,h,m,phi,theta_F,theta_R,theta_Fdot,theta_Rdot)
%PHIDDOT
%    PHIDDOT = PHIDDOT(I11,V,Vdot,DF,DR,G,H,M,PHI,theta_F,theta_R,theta_Fdot,theta_Rdot)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    27-Feb-2024 08:33:49

t2 = cos(phi);
t3 = cos(theta_F);
t4 = cos(theta_R);
t5 = sin(phi);
t6 = sin(theta_F);
t7 = sin(theta_R);
t8 = V.^2;
t9 = df.^2;
t10 = dr.^2;
t11 = t3.^2;
t12 = t4.^2;
phiddot = (h.*m.*1.0./(df+dr).^2.*(g.*t5.*t9.*t11+g.*t5.*t10.*t11+df.*dr.*g.*t5.*t11.*2.0+Vdot.*t2.*t7.*t9.*t11+V.*t2.*t4.*t10.*theta_Fdot+h.*t2.*t5.*t8.*t11+h.*t2.*t5.*t8.*t12+df.*t2.*t3.*t6.*t8.*t12-df.*t2.*t4.*t7.*t8.*t11+dr.*t2.*t3.*t6.*t8.*t12-dr.*t2.*t4.*t7.*t8.*t11-h.*t2.*t5.*t8.*t11.*t12.*2.0+Vdot.*df.*dr.*t2.*t7.*t11+V.*df.*dr.*t2.*t4.*theta_Fdot+Vdot.*t2.*t3.*t4.*t6.*t10+V.*t2.*t4.*t9.*t11.*theta_Rdot+Vdot.*df.*dr.*t2.*t3.*t4.*t6+V.*df.*dr.*t2.*t4.*t11.*theta_Rdot-V.*t2.*t3.*t6.*t7.*t10.*theta_Rdot-V.*df.*dr.*t2.*t3.*t6.*t7.*theta_Rdot-h.*t2.*t3.*t4.*t5.*t6.*t7.*t8.*2.0))./(t11.*(I11+h.^2.*m));
end
