function out1 = equb(thetas)

%EQUB
%    OUT1 = EQUB(theta_F,theta_R)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    05-Apr-2024 15:52:17

theta_F = thetas(1);
theta_R = thetas(2);

t2 = cos(theta_F);
t3 = cos(theta_R);
t4 = sin(theta_F);
t5 = sin(theta_R);
t10 = cos(1.0./1.0e+2);
t11 = sin(1.0./1.0e+2);
t6 = t2.^2;
t7 = t3.^2;
t8 = 1.0./t2;
t9 = t2.*t3.*2.0;
t15 = t10.^2;
t16 = t2.*t5.*t11;
t17 = t3.*t4.*t11;
t19 = t2.*t3.*t4.*t5.*5.5e+1;
t12 = -t7;
t13 = t6.*3.3e+1;
t14 = t7.*3.3e+1;
t18 = t6.*t7.*5.5e+1;
t22 = -t19;
t23 = -t16;
t24 = t6.*t15.*3.0;
t25 = t7.*t15.*3.0;
t28 = t2.*t4.*t7.*t11.*1.1e+1;
t29 = t3.*t5.*t6.*t11.*1.1e+1;
t30 = t6.*t7.*t15.*6.0;
t31 = t2.*t3.*t4.*t5.*t15.*5.0;
t20 = t6+t12;
t21 = -t18;
t26 = -t24;
t27 = -t25;
t32 = -t29;
t33 = t9+t17+t23;
t34 = t13+t14+t21+t22+t26+t27+t28+t30+t31+t32;
t35 = 1.0./t34;
t36 = t8.*t15.*t20.*t33.*t35.*(5.0./4.0);
t37 = -t36;
out1 = [t37,t37];
end
