function zdot = bicycle_dynamics_1(I11,I22,I33,Tr,V,df,dr,g,h,m,phi,phidot,psi,theta,thetadot)
%BICYCLE_DYNAMICS_1
%    ZDOT = BICYCLE_DYNAMICS_1(I11,I22,I33,Tr,V,DF,DR,G,H,M,PHI,PHIDOT,PSI,THETA,THETADOT)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    02-Mar-2024 15:58:35

t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
t6 = df+dr;
t7 = I22.^2;
t8 = V.^2;
t9 = df.^2;
t10 = df.^3;
t11 = dr.^2;
t12 = dr.^3;
t14 = h.^2;
t15 = h.^3;
t17 = m.^2;
t18 = phidot.^2;
t13 = t11.^2;
t16 = t14.^2;
t19 = t2.^2;
t20 = t2.^3;
t21 = t3.^2;
t22 = t3.^3;
t24 = t4.^2;
t25 = t5.^2;
t26 = t5.^3;
t28 = 1.0./t3;
t29 = 1.0./t6;
t33 = I11.*df.*h.*m.*t3.*t4.*t5.*2.0;
t34 = I11.*dr.*h.*m.*t3.*t4.*t5.*2.0;
t37 = df.*t3.*t4.*t5.*t15.*t17.*2.0;
t38 = dr.*t3.*t4.*t5.*t15.*t17.*2.0;
t23 = t21.^2;
t27 = t25.^2;
t30 = t25-1.0;
t31 = I11.*m.*t9.*t21;
t32 = I11.*df.*dr.*m.*t21.*2.0;
t35 = t9.*t14.*t17.*t21;
t36 = df.*dr.*t14.*t17.*t21.*2.0;
et1 = -I11.*Tr.*t10.*t22-I11.*Tr.*t12.*t22-I11.*Tr.*df.*t11.*t22.*3.0-I11.*Tr.*dr.*t9.*t22.*3.0-Tr.*m.*t10.*t14.*t22-Tr.*m.*t12.*t14.*t22-t3.*t8.*t11.*t14.*t17.*t19+t8.*t11.*t14.*t17.*t19.*t22+I11.*I22.*V.*df.*t5.*thetadot+I11.*I22.*V.*dr.*t5.*thetadot+I11.*V.*m.*t5.*t12.*thetadot-Tr.*df.*m.*t11.*t14.*t22.*3.0-Tr.*dr.*m.*t9.*t14.*t22.*3.0+V.*h.*phidot.*t2.*t5.*t31.*2.0+V.*df.*t5.*t16.*t17.*thetadot+V.*dr.*t5.*t16.*t17.*thetadot+V.*t5.*t12.*t14.*t17.*thetadot-dr.*g.*t2.*t4.*t5.*t35+dr.*h.*t4.*t5.*t18.*t31-I11.*I22.*V.*df.*t5.*t19.*thetadot+I11.*I33.*V.*df.*t5.*t19.*thetadot-I11.*I22.*V.*dr.*t5.*t19.*thetadot+I11.*I33.*V.*dr.*t5.*t19.*thetadot+I11.*V.*df.*m.*t5.*t11.*thetadot+I11.*V.*df.*m.*t5.*t14.*thetadot;
et2 = I22.*V.*df.*m.*t5.*t14.*thetadot+I11.*V.*dr.*m.*t5.*t14.*thetadot+I22.*V.*dr.*m.*t5.*t14.*thetadot+V.*df.*t5.*t11.*t14.*t17.*thetadot-V.*df.*t5.*t16.*t17.*t19.*thetadot-V.*dr.*t5.*t16.*t17.*t19.*thetadot-df.*dr.*t3.*t8.*t14.*t17.*t19+df.*dr.*t8.*t14.*t17.*t19.*t22+V.*t3.*t4.*t9.*t15.*t17.*thetadot+V.*t3.*t4.*t11.*t15.*t17.*thetadot-V.*t5.*t12.*t14.*t17.*t19.*thetadot-dr.*t4.*t5.*t8.*t15.*t17.*t19+t4.*t5.*t12.*t15.*t17.*t18.*t21+I11.*I22.*V.*df.*phidot.*t2.*t3.*t4.*2.0-I11.*I33.*V.*df.*phidot.*t2.*t3.*t4.*2.0-I11.*I22.*V.*df.*phidot.*t2.*t4.*t22.*2.0+I11.*I33.*V.*df.*phidot.*t2.*t4.*t22.*2.0+I11.*I22.*V.*dr.*phidot.*t2.*t3.*t4.*2.0-I11.*I33.*V.*dr.*phidot.*t2.*t3.*t4.*2.0-I11.*I22.*V.*dr.*phidot.*t2.*t4.*t22.*2.0+I11.*I33.*V.*dr.*phidot.*t2.*t4.*t22.*2.0;
et3 = -I11.*V.*df.*m.*t5.*t14.*t19.*thetadot-I22.*V.*df.*m.*t5.*t14.*t19.*thetadot+I33.*V.*df.*m.*t5.*t14.*t19.*thetadot-I11.*V.*dr.*m.*t5.*t14.*t19.*thetadot-I22.*V.*dr.*m.*t5.*t14.*t19.*thetadot+I33.*V.*dr.*m.*t5.*t14.*t19.*thetadot+I11.*V.*h.*m.*t3.*t4.*t9.*thetadot+I11.*V.*h.*m.*t3.*t4.*t11.*thetadot-I22.*dr.*h.*m.*t4.*t5.*t8.*t19+I33.*dr.*h.*m.*t4.*t5.*t8.*t19+I11.*h.*m.*t4.*t5.*t12.*t18.*t21+V.*df.*dr.*t3.*t4.*t15.*t17.*thetadot.*2.0+V.*df.*phidot.*t2.*t3.*t4.*t16.*t17.*2.0-V.*df.*phidot.*t2.*t4.*t16.*t17.*t22.*2.0+V.*dr.*phidot.*t2.*t3.*t4.*t16.*t17.*2.0-V.*dr.*phidot.*t2.*t4.*t16.*t17.*t22.*2.0-V.*df.*t5.*t11.*t14.*t17.*t19.*thetadot+V.*phidot.*t2.*t5.*t9.*t15.*t17.*t21.*2.0+V.*phidot.*t2.*t5.*t11.*t15.*t17.*t21.*2.0;
et4 = df.*t4.*t5.*t11.*t15.*t17.*t18.*t21.*2.0+dr.*t4.*t5.*t8.*t15.*t17.*t19.*t21+dr.*t4.*t5.*t9.*t15.*t17.*t18.*t21-g.*t2.*t4.*t5.*t12.*t14.*t17.*t21+I11.*V.*df.*m.*phidot.*t2.*t3.*t4.*t14.*2.0+I22.*V.*df.*m.*phidot.*t2.*t3.*t4.*t14.*2.0-I11.*V.*df.*m.*phidot.*t2.*t4.*t14.*t22.*2.0-I33.*V.*df.*m.*phidot.*t2.*t3.*t4.*t14.*2.0-I22.*V.*df.*m.*phidot.*t2.*t4.*t14.*t22.*2.0+I33.*V.*df.*m.*phidot.*t2.*t4.*t14.*t22.*2.0+I11.*V.*dr.*m.*phidot.*t2.*t3.*t4.*t14.*2.0+I22.*V.*dr.*m.*phidot.*t2.*t3.*t4.*t14.*2.0-I11.*V.*dr.*m.*phidot.*t2.*t4.*t14.*t22.*2.0-I33.*V.*dr.*m.*phidot.*t2.*t3.*t4.*t14.*2.0-I22.*V.*dr.*m.*phidot.*t2.*t4.*t14.*t22.*2.0+I33.*V.*dr.*m.*phidot.*t2.*t4.*t14.*t22.*2.0+I11.*V.*h.*m.*phidot.*t2.*t5.*t11.*t21.*2.0+I11.*df.*h.*m.*t4.*t5.*t11.*t18.*t21.*2.0;
et5 = I22.*dr.*h.*m.*t4.*t5.*t8.*t19.*t21-I33.*dr.*h.*m.*t4.*t5.*t8.*t19.*t21+V.*df.*dr.*phidot.*t2.*t5.*t15.*t17.*t21.*4.0-df.*g.*t2.*t4.*t5.*t11.*t14.*t17.*t21.*2.0+I11.*V.*df.*dr.*h.*m.*t3.*t4.*thetadot.*2.0+I11.*V.*df.*dr.*h.*m.*phidot.*t2.*t5.*t21.*4.0;
et6 = t2.*t4.*t8.*t35+t2.*t4.*t8.*t36+t2.*t4.*t7.*t8.*t27-t4.*t7.*t8.*t20.*t27+t2.*t4.*t8.*t25.*t35.*2.0-I33.^2.*t4.*t8.*t20.*t27+t2.*t4.*t8.*t16.*t17.*t25-t4.*t8.*t16.*t17.*t20.*t25-t2.*t4.*t11.*t18.*t25.*t35+g.*h.*t4.*t9.^2.*t17.*t23-I22.*I33.*t2.*t4.*t8.*t27+I22.*I33.*t4.*t8.*t20.*t27.*2.0-V.*dr.*phidot.*t19.*t25.*t35.*2.0+g.*h.*t4.*t13.*t17.*t23+Tr.*h.*m.*t2.*t5.*t13.*t22+I22.*m.*t2.*t4.*t8.*t11.*t27+I22.*m.*t2.*t4.*t8.*t14.*t25+I22.*m.*t2.*t4.*t8.*t14.*t27-I33.*m.*t2.*t4.*t8.*t11.*t27-I33.*m.*t2.*t4.*t8.*t14.*t27-I22.*m.*t4.*t8.*t14.*t20.*t25-I22.*m.*t4.*t8.*t14.*t20.*t27+I33.*m.*t4.*t8.*t14.*t20.*t25+I33.*m.*t4.*t8.*t14.*t20.*t27;
et7 = V.*h.*t2.*t13.*t17.*t21.*thetadot+df.*g.*h.*t4.*t12.*t17.*t23.*4.0+dr.*g.*h.*t4.*t10.*t17.*t23.*4.0+g.*h.*t4.*t9.*t11.*t17.*t23.*6.0-g.*h.*t4.*t13.*t17.*t25.*t30+df.*t2.*t3.*t8.*t15.*t17.*t26-df.*t3.*t8.*t15.*t17.*t20.*t26+dr.*t2.*t3.*t8.*t15.*t17.*t26-dr.*t3.*t8.*t15.*t17.*t20.*t26+g.*t5.*t10.*t14.*t17.*t22.*t24.*2.0+g.*t5.*t12.*t14.*t17.*t22.*t24.*2.0-g.*t4.*t9.*t15.*t17.*t25.*t30-g.*t4.*t11.*t15.*t17.*t25.*t30+h.*t2.*t3.*t5.*t8.*t12.*t17+h.*t2.*t5.*t8.*t10.*t17.*t22-t2.*t4.*t8.*t9.*t14.*t17.*t23+t2.*t4.*t8.*t11.*t14.*t17.*t21-t2.*t4.*t8.*t11.*t14.*t17.*t23+t2.*t4.*t8.*t11.*t14.*t17.*t25-t2.*t4.*t8.*t16.*t17.*t21.*t25+t4.*t8.*t16.*t17.*t20.*t21.*t25+I22.*df.*h.*m.*t2.*t3.*t8.*t26;
et8 = -I22.*df.*h.*m.*t3.*t8.*t20.*t26+I33.*df.*h.*m.*t3.*t8.*t20.*t26+I22.*dr.*h.*m.*t2.*t3.*t8.*t26-I22.*dr.*h.*m.*t3.*t8.*t20.*t26+I33.*dr.*h.*m.*t3.*t8.*t20.*t26-I22.*g.*h.*m.*t4.*t9.*t25.*t30-I22.*g.*h.*m.*t4.*t11.*t25.*t30+Tr.*df.*h.*m.*t2.*t5.*t12.*t22.*3.0+Tr.*dr.*h.*m.*t2.*t5.*t10.*t22+V.*df.*h.*t2.*t12.*t17.*t21.*thetadot.*3.0+V.*dr.*h.*t2.*t10.*t17.*t21.*thetadot+Tr.*h.*m.*t2.*t5.*t9.*t11.*t22.*3.0+I22.*m.*t2.*t4.*t8.*t9.*t21.*t25+I22.*m.*t2.*t4.*t8.*t11.*t21.*t25-I22.*m.*t2.*t4.*t8.*t14.*t21.*t25-I33.*m.*t2.*t4.*t8.*t9.*t21.*t25-I33.*m.*t2.*t4.*t8.*t11.*t21.*t25+I22.*m.*t4.*t8.*t14.*t20.*t21.*t25-I33.*m.*t4.*t8.*t14.*t20.*t21.*t25;
et9 = df.*dr.*g.*t4.*t15.*t17.*t25.*t30.*-2.0+V.*h.*t2.*t9.*t11.*t17.*t21.*thetadot.*3.0-df.*g.*h.*t4.*t12.*t17.*t25.*t30.*2.0-V.*phidot.*t12.*t14.*t17.*t19.*t21.*t25.*2.0-df.*dr.*t2.*t4.*t8.*t14.*t17.*t23.*2.0+df.*g.*t5.*t11.*t14.*t17.*t22.*t24.*6.0+dr.*g.*t5.*t9.*t14.*t17.*t22.*t24.*6.0+df.*h.*t2.*t3.*t5.*t8.*t11.*t17+df.*h.*t2.*t5.*t8.*t11.*t17.*t22.*2.0+dr.*h.*t2.*t5.*t8.*t9.*t17.*t22.*3.0-g.*h.*t4.*t9.*t11.*t17.*t25.*t30+df.*t2.*t3.*t5.*t8.*t15.*t17.*t24.*2.0-df.*t2.*t5.*t8.*t15.*t17.*t22.*t24.*2.0+dr.*t2.*t3.*t5.*t8.*t15.*t17.*t24.*2.0-dr.*t2.*t5.*t8.*t15.*t17.*t22.*t24.*2.0-g.*t4.*t9.*t15.*t17.*t19.*t21.*t25-g.*t4.*t11.*t15.*t17.*t19.*t21.*t25+t2.*t4.*t8.*t11.*t14.*t17.*t21.*t25-t2.*t4.*t13.*t14.*t17.*t18.*t21.*t25;
et10 = I22.*df.*dr.*g.*h.*m.*t4.*t25.*t30.*-2.0+I22.*df.*dr.*m.*t2.*t4.*t8.*t21.*t25.*2.0-I33.*df.*dr.*m.*t2.*t4.*t8.*t21.*t25.*2.0+I22.*df.*h.*m.*t2.*t3.*t8.*t24.*t26.*2.0-I33.*df.*h.*m.*t2.*t3.*t8.*t24.*t26.*2.0+I22.*dr.*h.*m.*t2.*t3.*t8.*t24.*t26.*2.0-I33.*dr.*h.*m.*t2.*t3.*t8.*t24.*t26.*2.0-I22.*g.*h.*m.*t4.*t9.*t19.*t21.*t25-I22.*g.*h.*m.*t4.*t11.*t19.*t21.*t25+I33.*g.*h.*m.*t4.*t9.*t19.*t21.*t25+I33.*g.*h.*m.*t4.*t11.*t19.*t21.*t25-V.*df.*phidot.*t11.*t14.*t17.*t19.*t21.*t25.*4.0-df.*dr.*g.*t4.*t15.*t17.*t19.*t21.*t25.*2.0-V.*phidot.*t3.*t4.*t11.*t15.*t17.*t19.*t26.*2.0+df.*dr.*t2.*t4.*t8.*t14.*t17.*t21.*t25.*4.0+V.*t2.*t3.*t4.*t5.*t12.*t14.*t17.*thetadot-df.*t2.*t4.*t12.*t14.*t17.*t18.*t21.*t25.*2.0;
et11 = I22.*df.*dr.*g.*h.*m.*t4.*t19.*t21.*t25.*-2.0+I33.*df.*dr.*g.*h.*m.*t4.*t19.*t21.*t25.*2.0-I22.*V.*h.*m.*phidot.*t3.*t4.*t11.*t19.*t26.*2.0+I33.*V.*h.*m.*phidot.*t3.*t4.*t11.*t19.*t26.*2.0-V.*df.*dr.*phidot.*t3.*t4.*t15.*t17.*t19.*t26.*2.0+V.*df.*t2.*t3.*t4.*t5.*t11.*t14.*t17.*thetadot.*2.0+V.*dr.*t2.*t3.*t4.*t5.*t9.*t14.*t17.*thetadot-I22.*V.*df.*dr.*h.*m.*phidot.*t3.*t4.*t19.*t26.*2.0+I33.*V.*df.*dr.*h.*m.*phidot.*t3.*t4.*t19.*t26.*2.0;
mt1 = [V.*cos(psi);V.*sin(psi);-(t28.*t29.*(et1+et2+et3+et4+et5))./(t31+t32+t33+t34+t35+t36+t37+t38+t16.*t17+I11.*I22-I11.*I22.*t19-I11.*I22.*t21+I11.*I33.*t19+I11.*m.*t11+I11.*m.*t14+I22.*m.*t14+t11.*t14.*t17-t16.*t17.*t19-t16.*t17.*t21-t11.*t14.*t17.*t19+t16.*t17.*t19.*t21+I11.*I22.*t19.*t21-I11.*I33.*t19.*t21-I11.*m.*t14.*t19-I11.*m.*t14.*t21-I22.*m.*t14.*t19-I22.*m.*t14.*t21+I33.*m.*t14.*t19+I11.*m.*t14.*t19.*t21+I22.*m.*t14.*t19.*t21-I33.*m.*t14.*t19.*t21+t11.*t14.*t17.*t19.*t21);V.*t5.*t28.*t29];
mt2 = [(t29.^2.*(et6+et7+et8+et9+et10+et11))./(t21.*(t31+t32+t33+t34+t35+t36+t37+t38+I11.*I22.*t25+t16.*t17.*t25+t11.*t14.*t17.*t21+t11.*t14.*t17.*t25-t16.*t17.*t19.*t25-I11.*I22.*t19.*t25+I11.*I33.*t19.*t25+I11.*m.*t11.*t21+I11.*m.*t11.*t25+I11.*m.*t14.*t25+I22.*m.*t14.*t25-I11.*m.*t14.*t19.*t25-I22.*m.*t14.*t19.*t25+I33.*m.*t14.*t19.*t25-t11.*t14.*t17.*t19.*t25))];
zdot = [mt1;mt2];
end
